version: '3'
services:
  app:
    build: ./docker/php 
    depends_on:
      - db
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./src/:/var/www/html
    links:
      - db
      - mailhog
  web:
    build: ./docker/nginx
    ports:
      - 8080:80
    depends_on:
      - app
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./src/:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - ./data/:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
