version: '3'
services:
  app:
    build: ./docker/php 
    depends_on:
      - db
    volumes:
      - ./src/:/var/www/html
    links:
      - db
  web:
    build: ./docker/nginx
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./src/:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
  db:
    image: mysql:5.7.19
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
      MYSQL_USER: librarian
      MYSQL_PASSWORD: password
